package Model;

/**
 *
 * @author Ivens
 */
public enum MessageType {
    KEEPALIVE,
    GIVECONTACTS,
    DOLOGIN,
    DOLOGOFF,
    SENDCONTACTS,
    ALIVE,
    REGISTER,
    REGISTERAPROVED,
    REGISTERNOTAPROVED,
    USERLOGGED,
    USERNOTLOGGED,
    USERLOGGEDOFF,
    UPDATEUSER,
    UPDATESUCESS,
    UPDATEFAIL,
    REGISTERCONTACT,
    CONTACTREGISTERED,
    CONTACTREGFAIL,
    REMOVECONTACT,
    REMOVECONTACTSUCESS,
    REMOVECONTACTFAIL
}
